### ISSUE TITLE
v1.2.0 now crashes on 1.21

### ISSUE THREAD

**Issue by zachup100** [Raxdiam/ToastBegone#4]
Just updated to 1.2.0 from 1.1.0, and my game now refuses to continue. Switching back to 1.1.0 works just fine.

Minecraft Version: ``1.21``
Mod Loader: ``Fabric - 0.16.0``, also tested ``0.16.2``
Launcher: ``PrismLauncher``

Crashlog:
```
Time: 2024-08-21 02:11:09
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'toastbegone'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/serializer/NightConfigSerializer
	at com.raxdiam.toastbegone.ToastBegoneMod.onInitializeClient(ToastBegoneMod.java:10)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.serializer.NightConfigSerializer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 11 more
```

**Comment by Raxdiam** [comment]
Version 1.2.0 is available again on Modrinth, as this issue should now be resolved

The reason why this was happening is that I was using a fork of Cloth Config API, which was embedded into ToastBegone's jar file.
When the official version of Cloth Config API exists in the mods folder alongside ToastBegone, it throws this exception because it defaults to using the official version instead of the embedded custom version (which contains a class that the official version does not have).
